---
# tasks file for mysql-replication-master
- name: Install required packages
  apt:
    pkg: "{{ item }}"
  with_items:
    - python-mysqldb

- shell: service mysql status
  register: serverstatus
  ignore_errors: yes

- name: Enable binary logging
  lineinfile:
    dest: "{{ mysql_conf_file }}"
    insertafter: '\[mysqld\]'
    line: "{{ item }}"
    state: present
  with_items:
    - "innodb_flush_log_at_trx_commit=1"
    - "sync_binlog=1"
    - "server-id=1"
    - "log-bin=mysql-bin.log"

- name: Restart mysql
  service:
    name: mysql
    state: restarted
  when: serverstatus.rc == 0

- name: Create replication user
  mysql_user:
    login_user: "{{ master_user }}"
    login_password: "{{ master_password }}"
    name: "{{ replication_user }}"
    password: "{{ replication_password }}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT/mysql.*:SELECT"
    host: "%"
    state: present
  when: serverstatus.rc == 0

- name: dump database
  mysql_db:
    login_user: "{{ master_user }}"
    login_password: "{{ master_password }}"
    name: "{{ item }}"
    state: dump
    target: "/tmp/{{ item }}.dmp.gz"
  with_items:
    - "{{ databases }}"
  when: serverstatus.rc == 0

- name: retrieve database dumps
  fetch:
    dest: "{{ control_dump_location }}"
    src: "/tmp/{{ item }}.dmp.gz"
    flat: yes
  with_items:
    - "{{ databases }}"
  when: serverstatus.rc == 0
